apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-presentation
  namespace: my-presentation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-presentation
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: k8s-presentation
    spec:
      containers:
        - name: k8s-presentation
          image: k8s-presentation:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: secret-password
                  name: presentation-secret
            - name: A_PARAM
              valueFrom:
                configMapKeyRef:
                  key: a-param
                  name: k8s-presentation
